services:
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # --- KRaft mode ---

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT_HOST://0.0.0.0:9092,PLAINTEXT_DOCKER://0.0.0.0:19092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:9092,PLAINTEXT_DOCKER://kafka:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_DOCKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_DOCKER



      # --- Storage ---
      KAFKA_LOG_DIRS: /var/lib/kafka/data

      # --- Single-node cluster ---
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # --- Required for first startup ---
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

    volumes:
      - kafka-data:/var/lib/kafka/data

    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
      interval: 5s
      timeout: 5s
      retries: 20

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    container_name: schema-registry
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

      # KRaft bootstrap
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:19092

      # Required for KRaft mode
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/subjects"]
      interval: 5s
      timeout: 5s
      retries: 20

  jobmanager:
    image: local/flink-kafka:1.19.3
    build:
      context: ./docker_flink_image
      dockerfile: flink-kafka.Dockerfile
    container_name: jobmanager
    command: jobmanager
    depends_on:
      kafka:
        condition: service_healthy
      producer:
        condition: service_started
    ports:
      - "8082:8081"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:19092
      KAFKA_INPUT_TOPIC: procstat_snapshots
      KAFKA_OUTPUT_TOPIC: procstat_metrics
      KAFKA_GROUP_ID: cpu-enrichment-consumer
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
      PARQUET_CONSUMER_GROUP_ID: parquet-writer-consumer
      PARQUET_OUTPUT_PATH: /opt/flink/output
    volumes:
      - ./flink:/opt/flink/usrlib
      - ./output:/opt/flink/output

  taskmanager:
    image: local/flink-kafka:1.19.3
    container_name: taskmanager
    command: taskmanager
    depends_on:
      - jobmanager
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:19092
      KAFKA_INPUT_TOPIC: procstat_snapshots
      KAFKA_OUTPUT_TOPIC: procstat_metrics
      KAFKA_GROUP_ID: cpu-enrichment-consumer
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
      PARQUET_CONSUMER_GROUP_ID: parquet-writer-consumer
      PARQUET_OUTPUT_PATH: /opt/flink/output
    volumes:
      - ./flink:/opt/flink/usrlib
      - ./output:/opt/flink/output

  producer:
    image: local/procstat-producer:latest
    build:
      context: .
      dockerfile: docker_producer_image/Dockerfile
    container_name: producer
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    environment:
      SLEEP_SECONDS: "60"
      KAFKA_BOOTSTRAP_SERVERS: kafka:19092
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
      TOPIC: procstat_snapshots
    restart: unless-stopped

volumes:
  kafka-data:
  flink:
  output:
